/// READING WHAT A PICKED FILE SAYS, BEFORE AURA CHANGES IT.
///
/// ## THE GAP THIS CLOSES
///
/// `ProfileMediaPipeline` runs a picked image through a crop editor and uploads
/// the editor's OUTPUT. That re-encode destroys any Content Credentials the
/// original carried, so 40 production rows — every avatar and cover on the
/// platform — reached storage with no provenance at all.
///
/// Losing the credential there is CORRECT. Its hash describes the original
/// bytes and no longer describes the cropped ones; carrying it forward would be
/// a false claim about a file it does not cover.
///
/// Forgetting what it said is not correct. The original is in memory at edit
/// time, which is the only moment anything can read it, and after that the
/// information is gone for good.
///
/// ## WHAT THIS DOES, AND WHAT IT DELIBERATELY DOES NOT
///
/// A substring scan for the IPTC `digitalsourcetype` vocabulary — the same
/// vocabulary the server reads, so the two cannot disagree about what a marker
/// means. It parses no container, validates no signature and reads no
/// assertion beyond the newscode itself.
///
/// The result is a CLIENT ASSERTION and is recorded as one. Aura did not
/// observe these bytes on its own server; a client said what it saw in a file
/// nobody else can now check, because the file it describes no longer exists.
/// That is weaker evidence than a server reading, and the model has a place for
/// exactly that distinction rather than a reason to pretend otherwise.
///
/// Non-AI codes are not scanned for at all. "The original said a camera took
/// it" must never become Aura asserting a human made the crop — the same
/// refusal the server-side reader makes, for the same reason.
library;

import 'dart:convert';
import 'dart:typed_data';

/// What the pre-edit original stated about its own origin.
enum SourceOriginClaim {
  /// The file stated it was generated by a trained algorithm.
  aiGenerated,

  /// The file stated it mixes trained-algorithm output with other material.
  aiAltered,
}

String sourceOriginWire(SourceOriginClaim c) =>
    c == SourceOriginClaim.aiGenerated ? 'AI_GENERATED' : 'AI_ALTERED';

/// The IPTC codes that state AI involvement.
///
/// ORDER IS LOAD-BEARING. `trainedAlgorithmicMedia` is a SUFFIX of
/// `compositeWithTrainedAlgorithmicMedia`, so testing the shorter first would
/// report an AI-assisted composite as fully AI-generated — a real misstatement
/// about someone's photograph produced by matching order alone.
const _aiCodes = <String, SourceOriginClaim>{
  'compositeWithTrainedAlgorithmicMedia': SourceOriginClaim.aiAltered,
  'trainedAlgorithmicMedia': SourceOriginClaim.aiGenerated,
};

/// How much of the head to read.
///
/// A C2PA manifest sits near the start of the file in every container the
/// specification defines, so this reaches it without walking a large image.
const int kSourceScanBytes = 262144;

/// Scan a picked file for what it says about its own origin.
///
/// Returns null when the file says nothing — which is most files, and is not a
/// finding. Absence of a marker is absence of information, never evidence that
/// a human made something.
SourceOriginClaim? scanSourceOrigin(Uint8List bytes) {
  if (bytes.length < 16) return null;

  final window = bytes.length <= kSourceScanBytes
      ? bytes
      : Uint8List.sublistView(bytes, 0, kSourceScanBytes);

  // latin1 maps every byte to a code unit, so a binary buffer becomes
  // searchable without a decode that could throw on invalid UTF-8.
  final hay = latin1.decode(window, allowInvalid: true);

  for (final entry in _aiCodes.entries) {
    if (hay.contains(entry.key)) return entry.value;
  }
  return null;
}
